# Generated by Django 4.2.11 on 2026-06-08 21:26

import apps.vendors.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_code",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("vendor_name", models.CharField(db_index=True, max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                (
                    "vendor_type",
                    models.CharField(blank=True, default="supplier", max_length=50),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("alternate_phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("address_line1", models.TextField()),
                ("address_line2", models.TextField(blank=True)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                ("country", models.CharField(default="India", max_length=100)),
                (
                    "gstin",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[apps.vendors.models.validate_gstin],
                        verbose_name="GSTIN",
                    ),
                ),
                (
                    "pan",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[apps.vendors.models.validate_pan],
                        verbose_name="PAN",
                    ),
                ),
                ("tan", models.CharField(blank=True, max_length=10)),
                ("msme_registered", models.BooleanField(default=False)),
                ("msme_number", models.CharField(blank=True, max_length=20)),
                ("bank_name", models.CharField(max_length=255)),
                ("bank_branch", models.CharField(blank=True, max_length=255)),
                ("account_number", models.CharField(max_length=20)),
                (
                    "ifsc_code",
                    models.CharField(
                        max_length=11, validators=[apps.vendors.models.validate_ifsc]
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("savings", "Savings"),
                            ("current", "Current"),
                            ("cash_credit", "Cash Credit"),
                        ],
                        default="current",
                        max_length=20,
                    ),
                ),
                ("account_holder_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending Approval"),
                            ("blacklisted", "Blacklisted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_terms",
                    models.IntegerField(default=30, help_text="Payment terms in days"),
                ),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vendors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
                "db_table": "vendors",
                "ordering": ["vendor_name"],
            },
        ),
    ]
