# Generated by Django 4.2.11 on 2026-06-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("ap_review", "AP Review"),
                            ("manager_review", "Manager Review"),
                            ("finance_review", "Finance Review"),
                            ("payment", "Payment"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("sent_back", "Sent Back"),
                            ("escalated", "Escalated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("action_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Approval",
                "verbose_name_plural": "Approvals",
                "db_table": "approvals",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("invoice_upload", "Invoice Upload"),
                            ("ocr_run", "OCR Processed"),
                            ("invoice_validated", "Invoice Validated"),
                            ("approval_action", "Approval Action"),
                            ("payment_created", "Payment Created"),
                            ("vendor_created", "Vendor Created"),
                            ("user_login", "User Login"),
                            ("user_logout", "User Logout"),
                            ("report_generated", "Report Generated"),
                            ("po_matched", "PO Matched"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("object_type", models.CharField(blank=True, max_length=50)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
