# Generated by Django 4.2.11 on 2026-06-08 21:26

import apps.invoices.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(db_index=True, max_length=100)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("payment_due_date", models.DateField(blank=True, null=True)),
                ("vendor_name_raw", models.CharField(blank=True, max_length=255)),
                ("vendor_gstin", models.CharField(blank=True, max_length=15)),
                ("vendor_address", models.TextField(blank=True)),
                (
                    "po_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "invoice_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.invoices.models.invoice_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png", "tiff", "tif"]
                            )
                        ],
                    ),
                ),
                ("ocr_data", models.JSONField(blank=True, default=dict)),
                ("ocr_confidence", models.FloatField(default=0.0)),
                ("ocr_processed", models.BooleanField(default=False)),
                ("ocr_error", models.TextField(blank=True)),
                ("line_items", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("ocr_complete", "OCR Complete"),
                            ("validated", "Validated"),
                            ("po_matched", "PO Matched"),
                            ("ap_approved", "AP Approved"),
                            ("manager_approved", "Manager Approved"),
                            ("finance_approved", "Finance Approved"),
                            ("payment_initiated", "Payment Initiated"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                            ("on_hold", "On Hold"),
                            ("duplicate", "Duplicate"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("not_matched", "Not Matched"),
                            ("two_way", "2-Way Matched"),
                            ("three_way", "3-Way Matched"),
                            ("partial", "Partially Matched"),
                            ("mismatch", "Mismatch"),
                        ],
                        default="not_matched",
                        max_length=20,
                    ),
                ),
                ("is_duplicate", models.BooleanField(default=False)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicate_invoices",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "invoices",
                "ordering": ["-created_at"],
            },
        ),
    ]
